spring:
  application:
    name: expense-tracker

  profiles:
    active: local

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_URL:http://localhost:1880}/realms/${KEYCLOAK_REALM:expense-realm}

  keycloak:
    server-url: ${KEYCLOAK_URL:http://localhost:1880}
    realm: ${KEYCLOAK_REALM:expense-realm}

  docker:
    compose:
      enabled: false

server:
  port: ${SERVER_PORT:1331}