spring:
  application:
    name: expense-tracker

  profiles:
    active: local

  flyway:
    enabled: true
    locations: classpath:db/migration

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8080/realms/expense-realm

  keycloak:
    server-url: http://localhost:8080
    realm: expense-realm

  docker:
    compose:
      enabled: false

server:
  port: 8081