server:
  port: 8081

spring:
  application:
    name: tracker

  docker:
    compose:
      enabled: false

  datasource:
    url: jdbc:mysql://localhost:3306/expense_be_db
    username: root
    password: password

  flyway:
    enabled: true

  jpa:
    hibernate:
      ddl-auto: none